name: pruebas
channels:
  - bioconda
  - schrodinger
  - defaults
  - conda-force
dependencies:
  - biopython=1.74=py37h1de35cc_0
  - blas=1.0=mkl
  - cd-hit=4.8.1=hd9629dc_0
  - clustalo=1.2.3=0
  - hyphy=2.5.8=h50e4897_1
  - iqtree=2.0.3=h7eed37d_0
  - pytest=5.2.4=py37_1
  - python=3.7.4=h359304d_1
  - requests=2.23.0
  - pytest-mock=3.3.1=py_0
