name: obi
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.74
  - blas=1.0
  - cd-hit=4.8.1
  - clustalo=1.2.3
  - coverage=5.3
  - hyphy=2.5.8
  - iqtree=2.0.3
  - pytest=5.2.4
  - python=3.7.4
  - requests=2.23.0
  - pytest-mock=3.3.1
  - blast=2.10.1
